title: Siavash Navehkesh
description: Purposeful data analytics professional with over 15 years of experience in business, systems and data analysis, design, and implementation. Adept at collaborating with business and technology stakeholders to solve complex problems with a customer-centric approach. An initiative-taking problem-solver with strong analytical and creative critical thinking skills who thrives in challenging situations and passionately strives for excellence, quality, and innovative solutions.
remote_theme: pages-themes/minimal@v0.2.0
logo: assets/img/portrait.png
